### ISSUE TITLE
Treffen nächste Woche

### ISSUE THREAD

**Issue by krakowski** [ProPra16/programmierpraktikum-abschlussprojekt-iuvba#1]
Hey Gruppe,

wir Tutoren wurden angewiesen uns im Idealfall einmal die Woche mit euch zu treffen.
Beim Treffen selbst könnt ihr beispielsweise Verständnisfragen zum Projekt oder allgemeine
Fragen zur Implementierung stellen. Das ganze sollte nicht länger als eine halbe Stunde dauern, jedoch
kann ich auch länger bleiben wenn ich gerade nichts zu tun hab und es erwünscht ist.

Für die Terminauswahl habe ich unter folgendem Link ein Doodle erstellt, bei dem ihr euren
Gruppennamen angeben und einen Termin auswählen sollt:

[http://doodle.com/poll/9wqkbsk8b7rt5hci](http://doodle.com/poll/9wqkbsk8b7rt5hci)

Insgesamt gibt es 16 Termine, es sollte sich also etwas finden.
Bei Fragen könnt ihr einfach hier im Issue antworten, ich werde dann per Mail benachrichtigt.

Viele Grüße,
Filip

**Comment by krakowski** [comment]
Hey,

habe gerade gesehen, dass ihr Montag 12:30 ausgewählt habt.
Folgende Räume scheinen zu diesem Termin frei zu sein:
- 25.13.U1.32
- 25.22.00.81
- 25.22.00.72

Sucht euch bitte einen dieser Räume aus und teilt mir dann hier mit
wo ihr euch treffen möchtet.

Viele Grüße,
Filip

**Comment by jeray100** [comment]
Am 2016-07-01 23:29, schrieb Filip Krakowski:

**Comment by krakowski** [comment]
Hey,

alles klar, ich warte dann dort. Falls der Raum wider Erwarten belegt sein sollte weichen wir auf einen
der anderen 2 Räume aus.

Viele Grüße,
Filip
